### ISSUE TITLE
Feature request to specify the domain of an option

### ISSUE THREAD

**Issue by timcera** [rubik/mando#16]
What I mean by the domain is the allowable values passed to an option.

For example:

```
:param mode <string ['test', 'debug', 'production', 'example']>:  This is the mode of the operation.
:param count <integer [0:10, 21]>:  The parameter count could be the numbers 0 through 10, or 21.
```

**Comment by rubik** [comment]
Uhm this would make for an interesting addition! On the other hand, it complicates the parsing quite a bit: I don't think such a thing should be done with regexes.

**Comment by timcera** [comment]
My examples were just brainstorming.  Could be setup instead like:

    :param mode <string> ['test', 'debug', 'production', 'example']:  This is the mode of the operation.

That way mando could extract just the domain with a separate regex, then process the remaining param string through the existing regex.  It would mean multiple regex matches, but probably not a big deal since the param strings are typically pretty short.

How to specify the domain of numbers?  In my first message I just made something up, but might be easier to just have Python logical expressions, '[count>0 and count<11 or count==21]'?  Or maybe that you would have to specify them in a list in the same way as a string domain, '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 21]'?  Maybe allow both?

With the domains as lists mando could have rather simple validation code.  Something like:

    if paramvar not in eval(domainvar):
        raise ValueError('{0} not in domain {1}'.format(paramvar, domainvar))

**Comment by rubik** [comment]
I wouldn't use `eval`, as that would introduce a security hole. The idea is interesting, but as of now I'm rather busy. If you want, you can draft up a pull request and I'll be happy to review it!

**Comment by MarioSchwalbe** [comment]
Did you notice that allowed lists of values are already supported by `ArgumentParser`? Works like that:
```
@command('list')
@arg('what', choices='jobs nodes queue plugins'.split())
def _list(what):
    '''
        List jobs/nodes/queue/plugins.
        :param what: what?
    '''
    ...
```

**Comment by rubik** [comment]
@MarioSchwalbe Pardon my late reply, but I don't ever recall of getting notified of your reply. In any case, the `choices` argument is what I've always used in my projects as well. Supporting inline Python expressions would be too much, and I don't want to add it. As you noted, one can always do further validation in the body of the function.
