### ISSUE TITLE
Support 'func(*args, **kwds)'

### ISSUE THREAD

**Issue by timcera** [rubik/mando#18]
I have a couple functions with a signature like:

    def func(*args, **kwds):
        print(args, kwds)

Even though I can call the function from within Python, the way mando checks for keyword arguments the above function isn't run because mando can't find the keyword.  The error is:

    wdmtoolbox: error: unrecognized arguments: --start_date=2014-02-22

Typical command line usage is:

    wdmtoolbox extract test.wdm 101 104 106 107 --start_date=2014-02-22

Where there can be a varying number of arguments.

I have tried a couple things, but nothing has worked so far.

    @mando.command
    @mando.arg('start_date')
    def func(*args, *kwds):
        print(args, kwds)

I also tried using "@mando.arg('--start_date')" because it isn't clear from the documentation whether to include the '--' or not.

Kindest regards,
Tim

**Comment by rubik** [comment]
In `@mando.arg` you would not include the two dashes. However, I have some doubts regarding this form: if you don't explicitly write the keyword arguments, mando cannot generate the help and the usage, because it does not know what the argument are. Moreover, in order to use `@mando.arg` the argument must already exist, either as positional or optional one. That decorator is used to add options to existing arguments, not to create them. I might have to make this clear in the documentation.

**Comment by timcera** [comment]
I have kept the API call of the function the same as the command line, but can't maintain that with variable number of arguments and having any named keywords.

The API call that I want (can have 1 or more numbers after the path):

    wdmtoolbox.extract('file.wdm', 101, 110, 300, 1, 24, start_date='2004-01-01')

The command line that I want:

    wdmtoolbox extract file.wdm 101 110 300 1 24 --start_date='2004-01-01'

The problem is that I can't have the same function since the function signatures are different.

API signature to get the API that way I want:

    def extract(*args, **kwds):
        # process args and kwds as needed
        pass

Command line signature to get the command line the way I want:

    def extract(start_date=None, end_date=None, *args):
        # process args as needed
        pass

Options that I have thought of:
* If mando could support using the API function signature.
* Use different functions, have an 'extract_api' function.
* Don't mix variable number of arguments with named keywords.

Any work-arounds or other ideas?

Kindest regards,
Tim

**Comment by rubik** [comment]
I think using the same function both as an API endpoint and a CLI entry point is bad design. I didn't quite understand why you need `**kwargs`. Are there other keyword arguments that the API needs but the CLI does not expose?

Could you do something along the lines of the following?

```python
def extract(*args, **kwargs):
    '''API endpoint'''


@mando.command('extract')
def extract_cli(file_name, *numbers, start_date=None, end_date=None):
    '''Extract numbers from file.

    :param file_name: The file name
    etc.''''
    extract(file_name, *numbers, start_date=start_date, end_date=end_date)
```

**Comment by rubik** [comment]
@timcera Have you had the chance to try it?

**Comment by timcera** [comment]
That would work, but that isn't what I want.

I use mando for four of my published applications, and have the API and command line interface match for all subcommands, except for the one time when I want variable number of arguments with named keyword argument(s).

For my 'wdmtoolbox extract ...' I will likely just remove the named keyword arguments if there isn't a different work-around.  If I take this approach then this:

    wdmtoolbox extract file.wdm 101 110 1003 21000 --start_date='2000-01-01'

would become:

    wdmtoolbox extract file.wdm 101 110 1003 21000 | tstoolbox date_slice --start_date='2000-01-01'

and within Python:

    from wdimtoolbox import wdmtoolbox
    from tstoolbox import tstoolbox
    df = wdmtoolbox.extract('file.wdm', 101, 110, 1003, 21000)  # returns Pandas DataFrame
    # then either:
    ndf = tstoolbox.date_slice(df, start_date='2000-01-01')
    # or
    ndf = df['2000-01-01':]

Kindest regards,
Tim

**Comment by rubik** [comment]
I think I can make it work. I'm very busy at the moment, but I'll try something in my spare time.

**Comment by timcera** [comment]
After looking at this again, and spending some time moving stuff around in my program, your suggestion is perfect.  Exactly what I wanted.  Apologies for taking so long to come around.  I had missed probably the simplest thing - that you could pass to mando.command the name of the sub-command.

Thanks,
Tim

**Comment by rubik** [comment]
I'm glad you found a convenient solution!
I apologize for the low activity here, but if you have suggestions or something else don't hesitate to open an issue. I'll do my best there.
