### ISSUE TITLE
Is there a way to have a default command?

### ISSUE THREAD

**Issue by brspurri** [rubik/mando#20]
I have the code:

```
@command('test'):
def test():
    print 'Testing...'

@command('run'):
def run():
    print 'Running...'

if __name__ == "__main__":
    main()
```

And I am trying to see if there is a way to run `run()` by default. 
For instance, instead of calling 

```
python myprogram.py run
Running...
```

I want to have the behavior such that:

```
python myprogram.py
Running...
```

I realize this doesn't seem to be a big deal to just add the `run` option. But in my scenario, I have another (non-python) program calling this current python script, and adding parameters isn't simple. I could obviously run the `run()` from main, but that would negate the ability of using `mando` to run my test method using `python myprogram.py test`.

Has anyone come across this?

**Comment by rubik** [comment]
Mhm there is probably a way to hack it so that it would work the way you intend.
However, I already considered this use case when I set out to build mando and decided against it.

Mando makes it easy to have multiple commands, but for other scenarios you might be better off with plain argparse. How many commands do you have?

**Comment by robertpeteuil** [comment]
Could you add something like this to your code:

```python
import sys
if not sys.argv[1:]:
    sys.argv.append('run')
```

**Comment by rubik** [comment]
@robertpeteuil I think that's an acceptable solution. I like leaving the user with the freedom to do what they want in this case. In one of my programs that uses Mando I do the same thing appending `--help` if no argument is given.
