### ISSUE TITLE
Handle all reStructuredText field lists

### ISSUE THREAD

**Issue by timcera** [rubik/mando#22]
At least this page http://www.sphinx-doc.org/en/stable/domains.html lists the following field lists:

param, parameter, arg, argument, key, keyword: Description of a parameter.
type: Type of a parameter. Creates a link if possible.
raises, raise, except, exception: That (and when) a specific exception is raised.
var, ivar, cvar: Description of a variable.
vartype: Type of a variable. Creates a link if possible.
returns, return: Description of the return value.
rtype: Return type. Creates a link if possible.

Examples from the same page:

   :param str sender: The person sending the message
   :param str recipient: The recipient of the message
   :param str message_body: The body of the message
   :param priority: The priority of the message, can be a number 1-5
   :type priority: integer or None
   :return: the message id
   :rtype: int
   :raises ValueError: if the message_body exceeds 160 characters
   :raises TypeError: if the message_body is not a basestring

**Comment by rubik** [comment]
Aside from `param` and `type`, what other fields can be useful for mando?

**Comment by timcera** [comment]
Good point.  I guess the only thing for mando is to allow for the synonyms to "param"; parameter, arg, argument, key, and keyword.  But maybe if mando uses Sphinx then that will be handled anyway.

**Comment by rubik** [comment]
Fixed by #24.
