### ISSUE TITLE
"Standard" reStructuredText would put the type before argument ":param int flag:"

### ISSUE THREAD

**Issue by timcera** [rubik/mando#23]
Mando currently has the type after the variable.

For example:

:param flag \<int\>: Flag is either up or down

However, the reStructuredText as described on this page http://www.sphinx-doc.org/en/stable/domains.html would use:

:param int flag: Flag is either up or down
OR
:param flag: Flag is either up or down
:type flag: int

**Comment by rubik** [comment]
With #21 we could ditch mando's format and only use reST. It's standard and more robutst. I think this is a good idea.

**Comment by rubik** [comment]
Fixed by #24.
