### ISSUE TITLE
Use inspect.signature for signature inspection

### ISSUE THREAD

**Issue by acetylen** [rubik/mando#46]
This was originally going to be an issue about using Python 3's argument annotations for type inference in addition to checking the docstring, but looking through the code I see that would be pretty annoying with the current implementation if you want to keep Python 2 compatibility.

Switching from `getfullargspec` to `signature` would remove a lot of the value juggling currently going on in `_generate_command`, since each value would contain the argument name, default value, and any annotations.This would in turn make it possible to get type information from the function signature itself, which would remove non-standard syntax from the docstring. 

However, it would also break Python 2 entirely. We're rapidly approaching the actual, final EOL of Python2 though, so maybe it's worth considering.

Sidenote:
I'm trying to migrate from argh as that library has some problems and unfortunately seems completely dead. Mando seems to do everything I want with a pain-free interface, and forcing developers to document by pulling parameter documentation from the docstring is a stroke of genius.

**Comment by rubik** [comment]
Hi Emil,

Right now Mando is used by Radon (another project of mine) and Radon also supports Python 2.7. I see that there's a backport of `inspect.signature` in the [`funcsigs`](https://funcsigs.readthedocs.io/en/0.4/) package. I think falling back to that if `inspect.signature` is not avaialble is a good solution. What do you think?

Also, would you be able to open a PR? I would be happy to review, right now I'm busy with my job so I can't write it myself.

**Comment by acetylen** [comment]
I could certainly have a look at it, but we'll see if anything comes of it. I'm also a bit short on time.
