### ISSUE TITLE
0.7.0: missing git version tag

### ISSUE THREAD

**Issue by kloczek** [rubik/mando#55]
According to https://pypi.org/project/mando/ latest version is 0.7.0.
Is it possible to add missing git tag?

**Comment by SpotlightKid** [comment]
Yes, please.

If releases are not tagged in git, hardly anybody will notice that there's a new version and distro packages won''t get updated etc..

**Comment by rubik** [comment]
@kloczek @SpotlightKid Thanks for pointing out this issue, it's been fixed.
